/**
 * Created by ww on 2015/7/20.
 */
/*
*二级菜单必须有子菜单，否则无效
* */
angular.module('app.value')
.value('menus',[
    {
        "name":"内容管理",
        "url":"app.contentMg",
        "subMenus":[
            {
                "name":"活动管理",
                "url":"",
                "subMenus":[
                    {
                        "name":"活动管理",
                        "url":"app.contentMg.activityMg"
                    }
                ]
            },
            {
                "name":"风格管理",
                "url":"",
                "subMenus":[
                    {
                        "name":"风格管理",
                        "url":"app.contentMg.styleMg"
                    },
                    {
                        "name":"预约管理",
                        "url":"app.contentMg.subscribeMg"
                    }
                ]
            },
            {
                "name":"服务管理",
                "url":"",
                "subMenus":[
                    {
                        "name":"项目管理",
                        "url":"app.contentMg.projectMg"
                    },
                    {
                        "name":"报价管理",
                        "url":"app.contentMg.quoteMg"
                    }
                ]
            }
        ]
    },
    {
        "name":"用户管理",
        "url":"app.userMg",
        "subMenus":[
            {
                "name":"用户管理",
                "url":"",
                "subMenus":[
                    {
                        "name":"用户列表",
                        "url":"app.userMg.userList"
                    },
                    {
                        "name":"用户积分管理",
                        "url":"app.userMg.pointsMg"
                    },
                    {
                        "name":"风格收藏管理",
                        "url":"app.userMg.styleCollectionMg"
                    },
                    {
                        "name":"用户消息管理",
                        "url":"app.userMg.userMsgMg"
                    }
                ]
            }
        ]
    },
    {
        "name":"系统设置",
        "url":"app.systemMg",
        "subMenus":[
            {
                "name":"员工管理",
                "url":"",
                "subMenus":[
                    {
                        "name":"员工管理",
                        "url":"app.systemMg.staffMg"
                    }
                ]
            }
        ]
    }
]
);
